package com.xa1y5k.tutorial.user;

public enum Status {
    SIKER,
    EZZEL_A_FELHASZNALONEVVEL_MAR_REGISZTRALTAK,
    SIKERTELEN,
    TUL_ROVID_FELHASZNALONEV,
    TUL_ROVID_JELSZO,
    CSAK_BETU_VAN_A_JELSZOBAN,
    CSAK_SZAM_VAN_A_JELSZOBAN,
    ADJA_MEG_A_NEVET
}
